name: weather_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  bloc: ^8.1.2
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed: ^2.4.2
  freezed_annotation: ^2.4.1
  google_fonts: ^5.1.0
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

dev_dependencies:
  build_runner: ^2.4.6

  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.23.0

flutter:
  uses-material-design: true
