name: weather_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  bloc: ^8.1.2
  dio: ^5.3.2
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.7
  freezed: ^2.4.2
  freezed_annotation: ^2.4.1
  geolocator: ^10.0.0
  google_fonts: ^5.1.0
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  permission_handler: ^10.4.3

dev_dependencies:
  build_runner: ^2.4.6

  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.23.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/eye.svg
    - assets/icons/eye_close.svg
    - assets/icons/wind.svg
    - assets/icons/drop.svg
    - assets/icons/pin.svg
    - assets/icons/CloudLightning.svg
    - assets/icons/CloudMoon.svg
    - assets/icons/CloudRain.svg
    - assets/icons/CloudSnow.svg
    - assets/icons/CloudSun.svg
    - assets/images/big_rain.png
    - assets/images/lightning_rain.png
    - assets/images/small_rain.png
    - assets/images/snow.png
    - assets/images/sun_rain.png
    - assets/images/sun.png











