// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYOOuO-00qQyGr5n1ydKTp2cYMgT3qvrs',
    appId: '1:151838551939:android:352f56b8cf1521b91990b6',
    messagingSenderId: '151838551939',
    projectId: 'auth-weather-app',
    storageBucket: 'auth-weather-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMCTT8NDMtdfDGKDOOhALKE0YfQRVSqZA',
    appId: '1:151838551939:ios:86945debc50257dc1990b6',
    messagingSenderId: '151838551939',
    projectId: 'auth-weather-app',
    storageBucket: 'auth-weather-app.appspot.com',
    androidClientId: '151838551939-s7vnquke4daik6vfhg25n6qcda9nhsnl.apps.googleusercontent.com',
    iosClientId: '151838551939-kugloorn88t2093l8icd52t39d316kib.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherApp',
  );
}
